const games=[['Soccer Random','https://unblocked-games-786.github.io/Soccer-Random/','game-images/soccer-random.png','sports'],['Basket Random','https://unblocked-games-786.github.io/Basket-Random/','game-images/basket-random.png','sports'],['Boxing Random','https://unblocked-games-786.github.io/Boxing-Random/','game-images/boxing-random.png','sports'],['Volley Random','https://unblocked-games-786.github.io/Volley-Random/','game-images/volley-random.png','sports'],['Run 3','https://lekug.github.io/tn6pS9dCf37xAhkJv/','game-images/run-3.png','arcade'],['Bad Time Simulator','https://sansflowey.github.io/bad-time/','game-images/bad-time-sim.png','arcade'],['Thirty Dollar Website','https://thirtydollar.website/','game-images/thirty-dollar-website.png','toy'],['OvO Modded','https://arjun99ab.github.io/ovo/1.4.5/','game-images/ovo-modded.png','arcade'],['Sandboxels','games/sandboxels.html','game-images/sandboxels.png','sandbox'],['Bloxorz','games/bloxorz.html','game-images/bloxorz.png','puzzle'],['Tiny Fishing','games/tiny-fishing.html','game-images/tiny-fishing.png','arcade'],['Cookie Clicker','games/cookie-clicker.html','game-images/cookie-clicker.png','idle']];
const $=s=>document.querySelector(s);function show(id){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==id);if(id!=='player')$('#gameframe').src='about:blank';scrollTo(0,0)}document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));
function render(){let q=$('#search').value.toLowerCase();let list=games.filter(g=>g[0].toLowerCase().includes(q));$('#total').textContent=list.length+' FOUND';$('#game-list').innerHTML=list.map((g,i)=>`<button class="game-row" data-i="${games.indexOf(g)}"><span class="index">${String(i+1).padStart(2,'0')}</span><span class="game-name">${g[0]}<small>${g[3]}</small></span><span class="game-preview"><span class="play">PLAY →</span>${g[2]?`<img src="${g[2]}" alt="${g[0]} preview" loading="lazy">`:'<span class="no-preview">NO IMAGE YET</span>'}</span></button>`).join('')||'<p class="none">no game by that name. tragic.</p>';document.querySelectorAll('.game-row').forEach(b=>b.onclick=()=>launch(games[+b.dataset.i]))}function launch(g){$('#player-title').textContent=g[0];$('#newtab').href=g[1];show('player');$('#gameframe').src=g[1]}$('#search').oninput=render;render();
$('#panic').onclick=()=>{window.open('https://www.google.com','_blank');window.close();setTimeout(()=>location.replace('https://www.google.com'),120)};
const metric=id=>document.getElementById(id);setInterval(()=>metric('clock').textContent=new Date().toLocaleTimeString(),1000);metric('clock').textContent=new Date().toLocaleTimeString();let frames=0,lastFps=performance.now();function countFrames(now){frames++;if(now-lastFps>=1000){metric('fps').textContent=frames;frames=0;lastFps=now}requestAnimationFrame(countFrames)}requestAnimationFrame(countFrames);async function checkPing(){let started=performance.now();try{await fetch('favicon.svg?ping='+Date.now(),{cache:'no-store'});metric('ping').textContent=Math.round(performance.now()-started)+'MS'}catch{metric('ping').textContent='OFFLINE'}}checkPing();setInterval(checkPing,15000);if(navigator.getBattery){navigator.getBattery().then(b=>{function battery(){metric('battery').textContent=Math.round(b.level*100)+'%'+(b.charging?'⚡':'')}battery();b.addEventListener('levelchange',battery);b.addEventListener('chargingchange',battery)})}else{metric('battery').textContent='N/A'}

const labInput=$('#lab-input'),labFrame=$('#lab-frame'),labStatus=$('#lab-status');$('#lab-run').onclick=()=>{const value=labInput.value.trim();if(!value){labStatus.textContent='you gotta paste something first :/';return}if(/^https?:\/\//i.test(value)){try{const url=new URL(value);labFrame.removeAttribute('srcdoc');labFrame.src=url.href;labStatus.textContent='loading link... if it stays blank, that site blocks embeds.'}catch{labStatus.textContent='that link got mangled :('}return}if(/^[a-z][a-z\d+.-]*:/i.test(value)){labStatus.textContent='only normal http:// or https:// links work here.';return}labFrame.removeAttribute('src');labFrame.srcdoc=value;labStatus.textContent='html running in the sandbox :D'};$('#lab-fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await labFrame.requestFullscreen()}catch{labStatus.textContent='fullscreen got blocked by this browser :('}};document.addEventListener('fullscreenchange',()=>{$('#lab-fullscreen').textContent=document.fullscreenElement?'EXIT FULLSCREEN':'FULLSCREEN'});$('#lab-clear').onclick=()=>{labInput.value='';labFrame.removeAttribute('src');labFrame.srcdoc='';labStatus.textContent='cleared. the code has returned to dust.'};

const audioToggle=$('#audio-toggle'),audioUpload=$('#audio-upload'),tempAudio=$('#temp-audio'),trackName=$('#track-name'),viz=$('#visualizer'),vizCtx=viz.getContext('2d');let audioCtx,analyser,source,loopTimer,objectUrl,isPlaying=false,usingUpload=false,step=0;const notes=[110,146.83,164.81,220,196,164.81,146.83,130.81];
function setupAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=64;analyser.smoothingTimeConstant=.78;analyser.connect(audioCtx.destination)}
function blip(freq,when){const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='square';osc.frequency.setValueAtTime(freq,when);gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(.055,when+.01);gain.gain.exponentialRampToValueAtTime(.0001,when+.19);osc.connect(gain).connect(analyser);osc.start(when);osc.stop(when+.2)}
function startLoop(){setupAudio();usingUpload=false;step=0;const tick=()=>{if(!isPlaying||usingUpload)return;blip(notes[step++%notes.length],audioCtx.currentTime);if(step%4===1)blip(55,audioCtx.currentTime);loopTimer=setTimeout(tick,240)};tick()}
function stopSound(){clearTimeout(loopTimer);tempAudio.pause();isPlaying=false;audioToggle.textContent='PLAY LOOP'}
audioToggle.onclick=async()=>{setupAudio();await audioCtx.resume();if(isPlaying){stopSound();audioToggle.textContent=usingUpload?'PLAY SONG':'PLAY LOOP';return}isPlaying=true;if(usingUpload){await tempAudio.play();audioToggle.textContent='PAUSE SONG'}else{startLoop();audioToggle.textContent='PAUSE LOOP'}};
audioUpload.onchange=async()=>{const file=audioUpload.files[0];if(!file)return;stopSound();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);tempAudio.src=objectUrl;usingUpload=true;trackName.textContent=file.name;setupAudio();if(!source){source=audioCtx.createMediaElementSource(tempAudio);source.connect(analyser)}await audioCtx.resume();try{await tempAudio.play();isPlaying=true;audioToggle.textContent='PAUSE SONG'}catch{audioToggle.textContent='PLAY SONG'}};
tempAudio.onended=()=>{if(!tempAudio.loop){isPlaying=false;audioToggle.textContent='PLAY SONG'}};
function drawViz(){requestAnimationFrame(drawViz);const w=viz.width,h=viz.height;vizCtx.fillStyle='#0a0304';vizCtx.fillRect(0,0,w,h);const data=new Uint8Array(analyser?analyser.frequencyBinCount:24);if(analyser)analyser.getByteFrequencyData(data);const count=data.length,bw=w/count;for(let i=0;i<count;i++){const idle=5+Math.sin(Date.now()/280+i*.8)*3,val=analyser?data[i]/255*(h-8):idle;vizCtx.fillStyle=i%3===0?'#ff9aa6':i%3===1?'#d94b5c':'#790f1d';vizCtx.fillRect(i*bw+1,h-val,Math.max(2,bw-2),val)}vizCtx.fillStyle='#f3d6d8';vizCtx.font='18px monospace';vizCtx.fillText(isPlaying?'AUDIO // LIVE':'AUDIO // IDLE',8,19)}drawViz();
