const games=[['Soccer Random','https://unblocked-games-786.github.io/Soccer-Random/','sports','⚽','two buttons, somehow a whole sport'],['Basket Random','https://unblocked-games-786.github.io/Basket-Random/','sports','🏀','basketball after physics left the room'],['Boxing Random','https://unblocked-games-786.github.io/Boxing-Random/','sports','🥊','professional flailing'],['Volley Random','https://unblocked-games-786.github.io/Volley-Random/','sports','🏐','volleyball, allegedly'],['Run 3','https://lekug.github.io/tn6pS9dCf37xAhkJv/','arcade','✦','the tunnel keeps getting worse'],['Bad Time Simulator','https://sansflowey.github.io/bad-time/','arcade','☠','the title is a warning'],['Thirty Dollar Website','https://thirtydollar.website/','toy','$','make noise for no useful reason'],['Ovo + Mods','https://arjun99ab.github.io/ovo/','arcade','O','ovo and the mod pile'],['Sandboxels','https://sandboxels.r74n.com/','sandbox','▦','questionable pixel science'],['Bloxorz','games/bloxorz.html','puzzle','▰','rectangle falls. you stare.'],['Tiny Fishing','games/tiny-fishing.html','arcade','◡','tiny pond, serious business'],['Cookie Clicker','games/cookie-clicker.html','idle','●','this many cookies seems unsafe']];
const $=s=>document.querySelector(s),views=[...document.querySelectorAll('.view')];let category='all';
function show(id){views.forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.view===id));if(id!=='player')$('#gameframe').src='about:blank';scrollTo(0,0)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#home').onclick=()=>show('landing');$('#enter').onclick=()=>show('games');
function render(){let q=$('#search').value.toLowerCase();let found=games.filter(g=>g[0].toLowerCase().includes(q)&&(category==='all'||g[2]===category));$('#grid').innerHTML=found.map((g,i)=>`<article><div class="num">${String(i+1).padStart(2,'0')} / ${g[2]}</div><div class="symbol">${g[3]}</div><h3>${g[0]}</h3><p>${g[4]}</p><button data-i="${games.indexOf(g)}">launch →</button></article>`).join('')||'<p class="nothing">nothing here. impressive search.</p>';document.querySelectorAll('#grid article button').forEach(b=>b.onclick=()=>launch(games[+b.dataset.i]))}
function launch(g){$('#player-title').textContent=g[3]+' '+g[0];$('#gameframe').src=g[1];$('#newtab').href=g[1];show('player');$('#gameframe').src=g[1]}$('#back').onclick=()=>show('games');
['all','sports','arcade','puzzle','sandbox','idle','toy'].forEach(c=>{let b=document.createElement('button');b.textContent=c;b.className=c==='all'?'on':'';b.onclick=()=>{category=c;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('on',x===b));render()};$('#filters').append(b)});$('#search').oninput=render;render();
function tick(){let d=new Date();$('#time').textContent=d.toLocaleTimeString([],{hour12:false});$('#date').textContent=d.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric',year:'numeric'}).toUpperCase()}tick();setInterval(tick,1000);$('#ping').textContent=Math.floor(18+Math.random()*25);if(navigator.getBattery)navigator.getBattery().then(b=>{let u=()=>$('#battery').textContent=Math.round(b.level*100)+'%';u();b.onlevelchange=u});
let words=['my corner.','the game pile.','something strange.','0D.'],wi=0;setInterval(()=>{wi=(wi+1)%words.length;$('#typed').textContent=words[wi]},3600);
