const FIREBASE_CONFIG={apiKey:'AIzaSyBHqyr2IqlJrbAvIwGMCkWRUULIh13nt38',authDomain:'goobernet-9129d.firebaseapp.com',projectId:'goobernet-9129d',storageBucket:'goobernet-9129d.firebasestorage.app',messagingSenderId:'971675065814',appId:'1:971675065814:web:562730d397bca5a9a15877',measurementId:'G-KEHCVWYRS7'};
const OWNER_UID='dbNR6VfIgbcqmhCJALehkkuWM3g2',ROOMS=['general','games','random'];

Promise.all([
 import('https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js'),
 import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js'),
 import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js')
]).then(([firebaseApp,firebaseAuth,firestore])=>{
 const app=firebaseApp.initializeApp(FIREBASE_CONFIG),auth=firebaseAuth.getAuth(app),db=firestore.getFirestore(app),provider=new firebaseAuth.GoogleAuthProvider();
 const isPrimaryOwner=user=>user?.uid===OWNER_UID;
 const isOwner=user=>isPrimaryOwner(user)||(!!user&&currentOwner);
 let currentOwner=false,currentOwnerName='',currentAdmin=false,currentAdminName='',adminRecords=[],adminUnsub=null,ownerDeviceRecords=[],ownerDeviceUnsub=null,latestAnnouncements=null,pollUnsubs=[],announcementsReady=false,chatAlertsReady=false,importantTimer=null,importantShownId='';
 let chatNickname='',chatColor='#ffd2d7',displayRole=localStorage.getItem('gooberDisplayRole')||'user',currentRoom='general',chatLimit=100,chatUnsub=null,presenceUnsub=null,moderationUnsub=null,presenceTimer=null,latestChatDocs=[],replyDraft=null,lastSentAt=0;
 const button=(text,className)=>{const el=document.createElement('button');el.type='button';el.className=className;el.textContent=text;return el};

 const signIn=$('#announce-signin'),signOut=$('#announce-signout'),authStatus=$('#announce-auth-status'),setup=$('#announce-setup'),uidBox=$('#announce-uid'),copyUid=$('#announce-copy-uid'),announceForm=$('#announce-form'),announceAuthor=$('#announce-author'),announceStatus=$('#announce-form-status'),announcementList=$('#announcement-list'),announceImage=$('#announce-image'),announceImportant=$('#announce-important'),ownerTools=$('#owner-announce-tools'),addPoll=$('#announce-add-poll'),pollFields=$('#announce-poll-fields'),pollQuestion=$('#announce-poll-question'),pollOptions=[...document.querySelectorAll('.poll-option')];
 const adminPanel=$('#admin-panel'),adminAddForm=$('#admin-add-form'),adminUid=$('#admin-uid'),adminName=$('#admin-name'),adminStatus=$('#admin-status'),adminList=$('#admin-list'),ownerDevicePanel=$('#owner-device-panel'),ownerDeviceForm=$('#owner-device-form'),ownerDeviceUid=$('#owner-device-uid'),ownerDeviceName=$('#owner-device-name'),ownerDeviceStatus=$('#owner-device-status'),ownerDeviceList=$('#owner-device-list');
 const importantBanner=$('#important-banner'),importantTitle=$('#important-title'),importantAuthor=$('#important-author'),importantText=$('#important-text');
 const chatGate=$('#chat-gate'),chatRoom=$('#chat-room'),chatJoin=$('#chat-join-form'),chatName=$('#chat-name'),chatColorInput=$('#chat-color'),chatJoinStatus=$('#chat-join-status'),chatWho=$('#chat-who'),chatMessages=$('#chat-messages'),chatSend=$('#chat-send-form'),chatInput=$('#chat-message'),chatSendStatus=$('#chat-send-status'),chatOwnerSignIn=$('#chat-owner-signin'),chatOwnerStatus=$('#chat-owner-status'),roomName=$('#chat-room-name'),loadOlder=$('#chat-load-older'),pins=$('#chat-pins'),onlineList=$('#online-list'),replyBox=$('#chat-reply-draft'),displayRoleSelect=$('#display-role');

 const staff=()=>isOwner(auth.currentUser)||currentAdmin;
 const role=()=>isOwner(auth.currentUser)?'owner':currentAdmin?'admin':'user';
 const visibleRole=()=>{const real=role();return real==='owner'?(displayRole==='owner'||displayRole==='admin'?displayRole:'user'):real==='admin'&&displayRole==='admin'?'admin':'user'};
 function syncDisplayRole(){const real=role(),choices=real==='owner'?[['owner','OWNER'],['admin','ADMIN'],['user','NORMAL CREATURE']]:real==='admin'?[['admin','ADMIN'],['user','NORMAL CREATURE']]:[['user','NORMAL CREATURE']];if(!choices.some(([value])=>value===displayRole))displayRole=real;displayRoleSelect.replaceChildren(...choices.map(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;return option}));displayRoleSelect.value=displayRole;displayRoleSelect.disabled=real==='user'}
 displayRoleSelect.onchange=()=>{displayRole=displayRoleSelect.value;localStorage.setItem('gooberDisplayRole',displayRole);if(chatNickname){chatWho.textContent=(visibleRole()==='owner'?'〘OWNER〙 ':visibleRole()==='admin'?'〘ADMIN〙 ':'')+chatNickname;updatePresence()}if(latestChatDocs.length)renderChat(latestChatDocs)};
 const signInGoogle=()=>firebaseAuth.signInWithPopup(auth,provider).catch(error=>{console.error(error);authStatus.textContent='sign-in got bonked :/';chatJoinStatus.textContent='sign-in got bonked :/'});
 signIn.onclick=signInGoogle;chatOwnerSignIn.onclick=signInGoogle;signOut.onclick=()=>firebaseAuth.signOut(auth);
 copyUid.onclick=async()=>{await navigator.clipboard.writeText(uidBox.textContent);copyUid.textContent='COPIED!!'};

 function showImportant(snapshot){const doc=snapshot.docs.find(item=>item.data().important===true);if(!doc||importantShownId===doc.id)return;importantShownId=doc.id;const data=doc.data(),close=()=>{clearTimeout(importantTimer);importantBanner.hidden=true};importantTitle.textContent=data.title||'IMPORTANT UPDATE';importantAuthor.textContent='BY '+(data.authorName||'THE OWNER');importantText.textContent=data.body||'';importantBanner.hidden=false;$('#important-open').onclick=()=>{show('announce');close()};$('#important-dismiss').onclick=close;importantTimer=setTimeout(close,30000)}

 function drawPoll(postDoc,data){const box=document.createElement('section'),head=document.createElement('div'),question=document.createElement('h4'),state=document.createElement('b'),options=document.createElement('div'),footer=document.createElement('div');box.className='poll-box';head.className='poll-head';question.textContent=data.pollQuestion;state.className='poll-state';state.textContent=data.pollOpen===false?'VOTE ENDED':'VOTE LIVE';options.className='poll-options';footer.className='poll-footer';head.append(question,state);box.append(head,options,footer);let chosen=null;
  const renderCounts=counts=>{options.replaceChildren(...data.pollOptions.map((option,index)=>{const choice=button('',`poll-choice${chosen===index?' chosen':''}`),label=document.createElement('span'),count=document.createElement('b');label.textContent=option;count.textContent=String(counts[index]||0);choice.append(label,count);choice.disabled=data.pollOpen===false||chosen!==null;choice.onclick=async()=>{try{let user=auth.currentUser;if(!user)user=(await firebaseAuth.signInAnonymously(auth)).user;await firestore.setDoc(firestore.doc(db,'announcements',postDoc.id,'votes',user.uid),{choice:index,voterUid:user.uid,createdAt:firestore.serverTimestamp()});chosen=index}catch(error){console.error(error);state.textContent=error.code==='permission-denied'?'YOU ALREADY VOTED':'VOTE GOT BONKED'}};return choice}))};renderCounts([]);
  pollUnsubs.push(firestore.onSnapshot(firestore.collection(db,'announcements',postDoc.id,'votes'),snapshot=>{const counts=data.pollOptions.map(()=>0);chosen=null;snapshot.docs.forEach(vote=>{const v=vote.data();if(Number.isInteger(v.choice)&&counts[v.choice]!==undefined)counts[v.choice]++;if(vote.id===auth.currentUser?.uid)chosen=v.choice});renderCounts(counts)}));
  if(data.pollOpen!==false&&(isOwner(auth.currentUser)||(currentAdmin&&data.authorUid===auth.currentUser?.uid))){const end=button('END VOTE','end-vote');end.onclick=async()=>{end.disabled=true;try{await firestore.updateDoc(postDoc.ref,{pollOpen:false})}catch(error){console.error(error);end.disabled=false;state.textContent='COULD NOT END IT'}};footer.append(end)}return box;
 }

 function drawAnnouncements(snapshot){pollUnsubs.forEach(unsub=>unsub());pollUnsubs=[];showImportant(snapshot);if(snapshot.empty){announcementList.innerHTML='<p class="announce-empty">no transmissions yet... suspicious.</p>';return}announcementList.replaceChildren(...snapshot.docs.map(postDoc=>{const data=postDoc.data(),article=document.createElement('article'),time=data.createdAt?.toDate?.(),admin=data.authorRole==='admin';article.className='announcement-card'+(admin?' admin-announcement':'')+(data.important?' important-announcement':'');const stamp=document.createElement('time'),title=document.createElement('h3'),body=document.createElement('p');stamp.textContent=time?time.toLocaleString():'TRANSMITTING...';title.textContent=data.title||'UNTITLED NOISE';body.textContent=data.body||'';article.append(stamp);const byline=document.createElement('small');byline.className='announcement-author';byline.textContent='BY '+(data.authorName||'UNKNOWN CREATURE');article.append(byline);if(admin){const badge=document.createElement('b');badge.className='admin-badge';badge.textContent='〘ADMIN〙 '+(data.authorName||'');article.append(badge)}if(data.important){const badge=document.createElement('b');badge.className='important-badge';badge.textContent='IMPORTANT UPDATE';article.append(badge)}article.append(title,body);if(typeof data.imageData==='string'&&data.imageData.startsWith('data:image/')){const image=document.createElement('img');image.className='announcement-image';image.src=data.imageData;image.alt='';article.append(image)}if(typeof data.pollQuestion==='string'&&Array.isArray(data.pollOptions)&&data.pollOptions.length>=2)article.append(drawPoll(postDoc,data));return article}))}
 firestore.onSnapshot(firestore.query(firestore.collection(db,'announcements'),firestore.orderBy('createdAt','desc')),snapshot=>{latestAnnouncements=snapshot;drawAnnouncements(snapshot);if(announcementsReady)snapshot.docChanges().filter(change=>change.type==='added').forEach(change=>{const data=change.doc.data();toast(data.important?'IMPORTANT UPDATE':'NEW ANNOUNCEMENT',data.title||'UNTITLED NOISE',(data.body||'').slice(0,90),'announce')});announcementsReady=true},error=>{console.error(error);announcementList.innerHTML='<p class="announce-empty">the transmission wire fell over :/</p>'});
 firestore.onSnapshot(firestore.query(firestore.collection(db,'chatMessages'),firestore.orderBy('createdAt','asc'),firestore.limitToLast(100)),snapshot=>{if(chatAlertsReady)snapshot.docChanges().filter(change=>change.type==='added').forEach(change=>{const data=change.doc.data();toast('GOOBERCHAT / '+String(data.room||'general').toUpperCase(),data.name||'unknown goober',(data.text||'').slice(0,90),'chat')});chatAlertsReady=true},error=>console.error(error));

 function shrinkImage(file){return new Promise((resolve,reject)=>{if(!file){resolve(null);return}if(file.size>12*1024*1024){reject(new Error('IMAGE_TOO_BIG'));return}const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);const make=(limit,quality)=>{const scale=Math.min(1,limit/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const context=canvas.getContext('2d');context.fillStyle='#100507';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',quality)};let data=make(1280,.76);if(data.length>680000)data=make(900,.58);data.length>680000?reject(new Error('IMAGE_TOO_BIG')):resolve(data)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('BAD_IMAGE'))};image.src=url})}
 addPoll.onchange=()=>{pollFields.hidden=!addPoll.checked};
 announceForm.onsubmit=async event=>{event.preventDefault();const owner=isOwner(auth.currentUser),authorName=announceAuthor.value.trim(),title=$('#announce-title').value.trim(),body=$('#announce-body').value.trim(),choices=pollOptions.map(input=>input.value.trim()).filter(Boolean);if(!authorName||!title||!body)return;if(addPoll.checked&&(!pollQuestion.value.trim()||choices.length<2)){announceStatus.textContent='THE VOTE NEEDS A QUESTION + 2 CHOICES';return}if(new Set(choices.map(choice=>choice.toLowerCase())).size!==choices.length){announceStatus.textContent='THE CHOICES CANNOT BE CLONES';return}announceStatus.textContent=owner&&announceImage.files[0]?'shrinking the image...':'transmitting...';try{const post={title,body,createdAt:firestore.serverTimestamp(),authorUid:auth.currentUser.uid,authorRole:owner?'owner':'admin',authorName};if(owner){const imageData=await shrinkImage(announceImage.files[0]);if(imageData)post.imageData=imageData;if(announceImportant.checked)post.important=true}if(addPoll.checked){post.pollQuestion=pollQuestion.value.trim();post.pollOptions=choices;post.pollOpen=true}await firestore.addDoc(firestore.collection(db,'announcements'),post);announceForm.reset();pollFields.hidden=true;announceStatus.textContent='TRANSMITTED!!'}catch(error){console.error(error);announceStatus.textContent=error.message==='IMAGE_TOO_BIG'?'image too enormous. use a smaller one :/':'posting got bonked or the rules need updating.'}};

 function drawAdmins(){adminList.replaceChildren(...adminRecords.map(record=>{const row=document.createElement('div'),text=document.createElement('span'),remove=button('REMOVE','admin-remove');row.className='admin-row';text.textContent=(record.name||'unnamed admin')+' — '+record.id;remove.onclick=async()=>{remove.disabled=true;try{await firestore.deleteDoc(firestore.doc(db,'admins',record.id))}catch(error){console.error(error);remove.disabled=false}};row.append(text,remove);return row}));if(!adminRecords.length)adminList.textContent='no admins. the blue council is empty.'}
 adminAddForm.onsubmit=async event=>{event.preventDefault();const uid=adminUid.value.trim(),name=adminName.value.trim();if(!uid||!name)return;adminStatus.textContent='summoning admin...';try{await firestore.setDoc(firestore.doc(db,'admins',uid),{name,addedAt:firestore.serverTimestamp(),addedBy:auth.currentUser.uid});adminAddForm.reset();adminStatus.textContent='ADMIN ADDED!!'}catch(error){console.error(error);adminStatus.textContent='admin summoning got bonked :/'}};
 function drawOwnerDevices(){ownerDeviceList.replaceChildren(...ownerDeviceRecords.map(record=>{const row=document.createElement('div'),text=document.createElement('span'),remove=button('REVOKE','owner-device-remove');row.className='owner-device-row';text.textContent=(record.name||'unnamed device')+' — '+record.id;remove.onclick=async()=>{remove.disabled=true;try{await firestore.deleteDoc(firestore.doc(db,'ownerDevices',record.id))}catch(error){console.error(error);remove.disabled=false}};row.append(text,remove);return row}));if(!ownerDeviceRecords.length)ownerDeviceList.textContent='no extra owner devices approved.'}
 ownerDeviceForm.onsubmit=async event=>{event.preventDefault();const uid=ownerDeviceUid.value.trim(),name=ownerDeviceName.value.trim();if(!uid||!name)return;ownerDeviceStatus.textContent='approving device...';try{await firestore.setDoc(firestore.doc(db,'ownerDevices',uid),{name,addedAt:firestore.serverTimestamp(),addedBy:auth.currentUser.uid});ownerDeviceForm.reset();ownerDeviceStatus.textContent='DEVICE APPROVED!!'}catch(error){console.error(error);ownerDeviceStatus.textContent='device approval got bonked :/'}};

 function appendRichText(parent,text){const parts=String(text).split(/(@[A-Za-z0-9_-]{1,30})/g);parts.forEach(part=>{if(part.startsWith('@')){const mark=document.createElement('mark');mark.textContent=part;parent.append(mark)}else parent.append(document.createTextNode(part))})}
 function setReply(data,id){replyDraft={id,name:data.name||'unknown goober',text:(data.text||'').slice(0,140)};replyBox.hidden=false;replyBox.querySelector('span').textContent='replying to '+replyDraft.name+': '+replyDraft.text;chatInput.focus()}
 replyBox.querySelector('button').onclick=()=>{replyDraft=null;replyBox.hidden=true};

 function renderPins(docs){const pinned=docs.filter(doc=>doc.data().pinned).slice(-3);pins.hidden=!pinned.length;pins.replaceChildren(...pinned.map(doc=>{const p=document.createElement('button'),data=doc.data();p.type='button';p.textContent='📌 '+(data.name||'goober')+': '+(data.text||'').slice(0,100);p.onclick=()=>document.querySelector(`[data-message-id="${doc.id}"]`)?.scrollIntoView({block:'center'});return p}))}
 function editMessage(doc,data,body,actions){const editor=document.createElement('textarea'),save=button('SAVE','chat-action'),cancel=button('CANCEL','chat-action');editor.className='chat-edit';editor.maxLength=5000;editor.value=data.text||'';body.replaceWith(editor);actions.replaceChildren(save,cancel);cancel.onclick=()=>renderChat(latestChatDocs);save.onclick=async()=>{const text=editor.value.trim();if(!text)return;save.disabled=true;try{await firestore.updateDoc(doc.ref,{text,editedAt:firestore.serverTimestamp()})}catch(error){console.error(error);save.disabled=false}};editor.focus()}
 function renderChat(docs){latestChatDocs=docs;const visible=docs.slice(-chatLimit);loadOlder.hidden=docs.length<=chatLimit;renderPins(docs);if(!visible.length){chatMessages.innerHTML='<p class="chat-empty">this room is empty. make a noise.</p>';return}const nearBottom=chatMessages.scrollHeight-chatMessages.scrollTop-chatMessages.clientHeight<90;chatMessages.replaceChildren(...visible.map(doc=>{const data=doc.data(),trueOwner=data.authorUid===OWNER_UID||data.authorRole==='owner',shownRole=data.displayRole||data.authorRole,owner=shownRole==='owner',admin=shownRole==='admin',mine=data.authorUid===auth.currentUser?.uid,row=document.createElement('article'),head=document.createElement('div'),name=document.createElement('b'),stamp=document.createElement('time'),body=document.createElement('p'),actions=document.createElement('div');row.dataset.messageId=doc.id;row.className='chat-message'+(owner?' owner-message':admin?' admin-message':'')+(data.pinned?' pinned-message':'');name.textContent=data.name||'unknown goober';if(!owner&&!admin)name.style.color=/^#[0-9a-f]{6}$/i.test(data.nameColor||'')?data.nameColor:'#ffd2d7';stamp.textContent=data.createdAt?.toDate?.().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})||'sending...';head.append(name);if(owner||admin){const badge=document.createElement('span');badge.className=owner?'owner-badge':'admin-badge';badge.textContent=owner?'〘OWNER〙':'〘ADMIN〙';head.append(badge)}head.append(stamp);if(data.replyTo){const quote=document.createElement('button');quote.type='button';quote.className='reply-quote';quote.textContent='↳ '+data.replyTo.name+': '+data.replyTo.text;row.append(head,quote)}else row.append(head);appendRichText(body,data.text||'');if(data.editedAt){const edited=document.createElement('small');edited.textContent=' edited';body.append(edited)}row.append(body);actions.className='chat-actions';const reply=button('REPLY','chat-action');reply.onclick=()=>setReply(data,doc.id);actions.append(reply);if(mine){const edit=button('EDIT','chat-action'),del=button('DELETE','chat-action');edit.onclick=()=>editMessage(doc,data,body,actions);del.onclick=()=>firestore.deleteDoc(doc.ref);actions.append(edit,del)}else if(isOwner(auth.currentUser)||(currentAdmin&&!trueOwner)){const del=button('DELETE','chat-action');del.onclick=()=>firestore.deleteDoc(doc.ref);actions.append(del)}if(staff()&&(isOwner(auth.currentUser)||!trueOwner)){const pin=button(data.pinned?'UNPIN':'PIN','chat-action');pin.onclick=()=>firestore.updateDoc(doc.ref,{pinned:!data.pinned});actions.append(pin)}row.append(actions);return row}));if(nearBottom)chatMessages.scrollTop=chatMessages.scrollHeight}

 function watchRoom(){if(chatUnsub)chatUnsub();chatLimit=100;roomName.textContent='# '+currentRoom.toUpperCase();document.querySelectorAll('.room-button').forEach(item=>item.classList.toggle('active',item.dataset.room===currentRoom));chatMessages.innerHTML='<p class="chat-empty">opening room...</p>';chatUnsub=firestore.onSnapshot(firestore.collection(db,'chatMessages'),snapshot=>{const docs=snapshot.docs.filter(doc=>(doc.data().room||'general')===currentRoom).sort((a,b)=>(a.data().createdAt?.toMillis?.()||0)-(b.data().createdAt?.toMillis?.()||0));renderChat(docs)},error=>{console.error(error);chatMessages.innerHTML='<p class="chat-empty">the room wire fell over :/</p>'});updatePresence()}
 document.querySelectorAll('.room-button').forEach(item=>item.onclick=()=>{currentRoom=item.dataset.room;replyDraft=null;replyBox.hidden=true;watchRoom()});
 loadOlder.onclick=()=>{chatLimit+=100;renderChat(latestChatDocs)};

 async function updatePresence(){if(!auth.currentUser||!chatNickname)return;try{await firestore.setDoc(firestore.doc(db,'presence',auth.currentUser.uid),{name:chatNickname,nameColor:chatColor,room:currentRoom,role:visibleRole(),lastSeen:firestore.serverTimestamp()})}catch(error){console.error(error)}}
 function watchPresence(){if(presenceUnsub)presenceUnsub();presenceUnsub=firestore.onSnapshot(firestore.collection(db,'presence'),snapshot=>{const now=Date.now(),people=snapshot.docs.map(doc=>({id:doc.id,...doc.data()})).filter(person=>person.room===currentRoom&&now-(person.lastSeen?.toMillis?.()||0)<90000);onlineList.replaceChildren(...people.map(person=>{const row=document.createElement('div'),name=document.createElement('span');row.className='online-user';name.textContent=person.name||'unknown goober';if(person.role==='owner')row.classList.add('owner-online');else if(person.role==='admin')row.classList.add('admin-online');else name.style.color=/^#[0-9a-f]{6}$/i.test(person.nameColor||'')?person.nameColor:'#ffd2d7';row.append(name);if(staff()&&person.role==='user'&&person.id!==auth.currentUser?.uid){const controls=document.createElement('div'),five=button('5M','mute-button'),hour=button('1H','mute-button'),unmute=button('UNMUTE','mute-button');five.onclick=()=>muteUser(person,5);hour.onclick=()=>muteUser(person,60);unmute.onclick=()=>unmuteUser(person);controls.append(five,hour,unmute);row.append(controls)}return row}));if(!people.length)onlineList.textContent='nobody. tumbleweed.'})}
 async function muteUser(person,minutes){try{await firestore.setDoc(firestore.doc(db,'moderation',person.id),{name:person.name||'unknown',mutedUntil:firestore.Timestamp.fromMillis(Date.now()+minutes*60000),mutedBy:auth.currentUser.uid});chatSendStatus.textContent=person.name+' muted for '+minutes+'m'}catch(error){console.error(error);chatSendStatus.textContent='mute button got bonked :/'}}
 async function unmuteUser(person){try{await firestore.deleteDoc(firestore.doc(db,'moderation',person.id));chatSendStatus.textContent=person.name+' unmuted'}catch(error){console.error(error);chatSendStatus.textContent='unmute got bonked :/'}}

 chatJoin.onsubmit=async event=>{event.preventDefault();chatNickname=chatName.value.trim().replace(/\s+/g,' ').slice(0,30);chatColor=chatColorInput.value;if(!chatNickname)return;chatJoinStatus.textContent='joining...';try{if(!auth.currentUser)await firebaseAuth.signInAnonymously(auth);sessionStorage.setItem('gooberChatName',chatNickname);localStorage.setItem('gooberChatColor',chatColor);chatWho.textContent=(visibleRole()==='owner'?'〘OWNER〙 ':visibleRole()==='admin'?'〘ADMIN〙 ':'')+chatNickname;chatGate.hidden=true;chatRoom.hidden=false;chatJoinStatus.textContent='';watchRoom();watchPresence();clearInterval(presenceTimer);presenceTimer=setInterval(updatePresence,30000);chatInput.focus()}catch(error){console.error(error);chatJoinStatus.textContent='anonymous sign-in needs to be enabled in Firebase.'}};
 chatSend.onsubmit=async event=>{event.preventDefault();const text=chatInput.value.trim();if(!text||!auth.currentUser)return;const now=Date.now();if(now-lastSentAt<1500){chatSendStatus.textContent='give the keyboard 1.5 seconds to breathe';return}lastSentAt=now;chatSendStatus.textContent='sending...';try{const message={name:chatNickname,nameColor:chatColor,text,room:currentRoom,createdAt:firestore.serverTimestamp(),authorUid:auth.currentUser.uid,authorRole:role(),displayRole:visibleRole(),pinned:false};if(replyDraft)message.replyTo=replyDraft;await firestore.addDoc(firestore.collection(db,'chatMessages'),message);chatInput.value='';replyDraft=null;replyBox.hidden=true;chatSendStatus.textContent=''}catch(error){console.error(error);chatSendStatus.textContent=error.code==='permission-denied'?'you are muted or the rules need updating :/':'message got bonked :/'}};
 $('#chat-leave').onclick=async()=>{if(auth.currentUser)firestore.deleteDoc(firestore.doc(db,'presence',auth.currentUser.uid)).catch(()=>{});clearInterval(presenceTimer);chatNickname='';chatRoom.hidden=true;chatGate.hidden=false;if(chatUnsub)chatUnsub();if(presenceUnsub)presenceUnsub()};
 const savedName=sessionStorage.getItem('gooberChatName'),savedColor=localStorage.getItem('gooberChatColor');if(savedName)chatName.value=savedName;if(savedColor){chatColor=savedColor;chatColorInput.value=savedColor}

 firebaseAuth.onAuthStateChanged(auth,async user=>{const primary=isPrimaryOwner(user),googleUser=!!user&&!user.isAnonymous;if(adminUnsub){adminUnsub();adminUnsub=null}if(ownerDeviceUnsub){ownerDeviceUnsub();ownerDeviceUnsub=null}currentOwner=primary;currentOwnerName='';currentAdmin=false;currentAdminName='';if(user&&!primary){try{const ownerDoc=await firestore.getDoc(firestore.doc(db,'ownerDevices',user.uid));currentOwner=ownerDoc.exists();currentOwnerName=ownerDoc.data()?.name||''}catch(error){console.error(error)}}const owner=isOwner(user);if(user&&!owner){try{const adminDoc=await firestore.getDoc(firestore.doc(db,'admins',user.uid));currentAdmin=adminDoc.exists();currentAdminName=adminDoc.data()?.name||''}catch(error){console.error(error)}}if(owner){adminUnsub=firestore.onSnapshot(firestore.collection(db,'admins'),snapshot=>{adminRecords=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));drawAdmins()})}if(primary){ownerDeviceUnsub=firestore.onSnapshot(firestore.collection(db,'ownerDevices'),snapshot=>{ownerDeviceRecords=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));drawOwnerDevices()})}const hasStaff=owner||currentAdmin;syncDisplayRole();signIn.hidden=googleUser;signOut.hidden=!googleUser;setup.hidden=!user;announceForm.hidden=!hasStaff;ownerTools.hidden=!owner;adminPanel.hidden=!owner;ownerDevicePanel.hidden=!primary;authStatus.textContent=primary?'signed in as the primary owner':currentOwner?'〘OWNER DEVICE〙 '+(currentOwnerName||'approved device'):currentAdmin?'〘ADMIN〙 signed in as '+(currentAdminName||user?.displayName||'blue creature'):user?'copy your code and send it to the owner':'viewing as a creature';uidBox.textContent=user?user.uid:'';chatOwnerSignIn.hidden=googleUser;chatOwnerStatus.textContent=owner?'OWNER MODE READY':currentAdmin?'ADMIN MODE READY':'not in staff mode';if(chatNickname){chatWho.textContent=(visibleRole()==='owner'?'〘OWNER〙 ':visibleRole()==='admin'?'〘ADMIN〙 ':'')+chatNickname;updatePresence()}if(latestAnnouncements)drawAnnouncements(latestAnnouncements);if(latestChatDocs.length)renderChat(latestChatDocs)});
}).catch(error=>{console.error(error);$('#announcement-list').innerHTML='<p class="announce-empty">firebase refused to wake up :/</p>';$('#chat-join-status').textContent='firebase refused to wake up :/'});
